# Generated by Django 4.2.4 on 2023-08-18 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=500)),
                ('sold', models.BooleanField(default=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)])),
                ('type', models.CharField(choices=[('record', 'Record'), ('clothing', 'Clothing'), ('poster', 'Poster'), ('miscellaneous', 'Miscellaneous')], default='Records', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='band',
            name='biography',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
