# Generated by Django 4.2.4 on 2023-08-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_merch_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock'), ('DANCE', 'Dance'), ('POP', 'Pop'), ('R&B', 'Rnb'), ('CHRISTIAN', 'Christian'), ('COUNTRY', 'Country'), ('ROCK', 'Rock'), ('ELECTRONIC', 'Electronic'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('HM', 'Heavy Metal'), ('INDIE', 'Indie'), ('FOLK', 'Folk'), ('REGGAE', 'Reggae'), ('BLUES', 'Blues'), ('LATIN', 'Latin'), ('FUNK', 'Funk'), ('PUNK', 'Punk'), ('DISCO', 'Disco'), ('HIPSTER', 'Hipster'), ('GRUNGE', 'Grunge'), ('TECHNO', 'Techno'), ('COUNTRY_ROCK', 'Country Rock'), ('TRAP', 'Trap'), ('SALSA', 'Salsa'), ('SOUNDTRACK', 'Soundtrack'), ('PSYCHEDELIC', 'Psychedelic'), ('RAP', 'Rap'), ('GOSPEL', 'Gospel'), ('NEW_WAVE', 'New Wave'), ('EDM', 'Edm'), ('TRANCE', 'Trance'), ('EMO', 'Emo'), ('FUSION', 'Fusion'), ('ALTERNATIVE_POP', 'Alternative Pop'), ('SINGER_SONGWRITER', 'Singer Songwriter'), ('RAGGAE', 'Raggae'), ('HARD_ROCK', 'Hard Rock'), ('SOUL', 'Soul'), ('RANCHERA', 'Ranchera'), ('ELECTRO_POP', 'Electro Pop'), ('SYMPHONIC', 'Symphonic'), ('REGGAETON', 'Reggaeton'), ('BOLLYWOOD', 'Bollywood')], default='HH', max_length=25),
        ),
    ]
